// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-xyp2j-RT664j0W9Hh7hWQzV7OGkQW0',
    appId: '1:316959182880:web:ef7bf57c842ad1e2dfac45',
    messagingSenderId: '316959182880',
    projectId: 'harmony-1a042',
    authDomain: 'harmony-1a042.firebaseapp.com',
    storageBucket: 'harmony-1a042.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP6wcseDXGGQLbJ1O2g60qfZ98yOPh2as',
    appId: '1:316959182880:android:9d634b86a01d618adfac45',
    messagingSenderId: '316959182880',
    projectId: 'harmony-1a042',
    storageBucket: 'harmony-1a042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU9eM7LkXGwoNiVwcd9QXQv8X90itDXQw',
    appId: '1:316959182880:ios:51ee0705637764dddfac45',
    messagingSenderId: '316959182880',
    projectId: 'harmony-1a042',
    storageBucket: 'harmony-1a042.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}