// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
   //Contack harrsion for info
    apiKey: 'AIzaSyCvT1SGRvPogSwx9ZDbONi1D8Qy9mLHxdU',
    appId: '1:670257855909:android:6688d075f48a90da257c4c',
    messagingSenderId: '670257855909',
    projectId: 'eecs-582-project-74abe',
    storageBucket: 'eecs-582-project-74abe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    //Contack harrsion for info
    apiKey: 'AIzaSyA8o2JGXDjfQ68iex2eUFWw7DvKTaX7Aeo',
    appId: '1:670257855909:ios:cf987a48c2e688bf257c4c',
    messagingSenderId: '670257855909',
    projectId: 'eecs-582-project-74abe',
    storageBucket: 'eecs-582-project-74abe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}
